In [1]:
import pandas as pd

df = pd.read_csv("../financial/Customer_Financial_Profiles.csv")

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nFirst 5 Rows:")
display(df.head())

Shape: (20000, 21)

Columns:
['id', 'current_age', 'birth_year', 'birth_month', 'gender', 'address', 'per_capita_income', 'yearly_income', 'total_debt', 'credit_score', 'num_credit_cards', 'transaction_id', 'date', 'client_id', 'card_id', 'amount', 'use_chip', 'merchant_id', 'merchant_city', 'merchant_state', 'zip']

Data Types:
id                     int64
current_age            int64
birth_year             int64
birth_month            int64
gender                   str
address                  str
per_capita_income      int64
yearly_income          int64
total_debt             int64
credit_score           int64
num_credit_cards       int64
transaction_id         int64
date                     str
client_id                str
card_id                  str
amount               float64
use_chip                 str
merchant_id              str
merchant_city            str
merchant_state           str
zip                    int64
dtype: object

Missing Values:
id                   0
current_age          0
birth_year           0
birth_month          0
gender               0
address              0
per_capita_income    0
yearly_income        0
total_debt           0
credit_score         0
num_credit_cards     0
transaction_id       0
date                 0
client_id            0
card_id              0
amount               0
use_chip             0
merchant_id          0
merchant_city        0
merchant_state       0
zip                  0
dtype: int64

Duplicate Rows:
0

First 5 Rows:

,id,current_age,birth_year,birth_month,gender,address,per_capita_income,yearly_income,total_debt,credit_score,...,transaction_id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip
0,1,64,1961,3,Female,"Street 286, Indore, Madhya Pradesh - 452645",86125,1033501,280435,715,...,1251,2024-03-28,CLTIND00104,CRD001042,1483.94,Yes,MCH00496,Mumbai,Maharashtra,452645
1,2,39,1986,12,Female,"Street 268, Kolkata, West Bengal - 700555",68414,820965,0,834,...,9976,2025-09-20,CLTIND00213,CRD002132,1274.72,Yes,MCH00374,Mumbai,Maharashtra,700555
2,3,50,1975,7,Female,"Street 262, Lucknow, Uttar Pradesh - 226797",22595,271138,0,609,...,6084,2024-10-02,CLTIND03292,CRD032922,7622.04,No,MCH00108,Kolkata,West Bengal,226797
3,4,27,1998,2,Male,"Street 265, Nagpur, Maharashtra - 440623",24158,289898,0,782,...,3350,2023-09-02,CLTIND05205,CRD052053,3970.48,Yes,MCH00001,Indore,Madhya Pradesh,440623
4,5,45,1980,7,Other,"Street 157, Delhi, Delhi - 110965",45475,545697,117821,608,...,11725,2025-05-25,CLTIND04910,CRD049101,418.45,No,MCH00254,Bengaluru,Karnataka,110965

In [2]:
# Detailed financial dataset inspection

print("=== MISSING VALUES ===")
print(df.isnull().sum())

print("\n=== DATA TYPES ===")
print(df.dtypes)

print("\n=== UNIQUE VALUES ===")
print(df.nunique())

print("\n=== NUMERIC SUMMARY ===")
display(df.describe().T)

print("\n=== CATEGORICAL VALUES ===")

for col in [
    "gender",
    "use_chip",
    "merchant_state"
]:
    print(f"\n{col}:")
    print(df[col].value_counts(dropna=False).head(20))

print("\n=== SAMPLE RECORDS ===")
display(df.head(10))

=== MISSING VALUES ===
id                   0
current_age          0
birth_year           0
birth_month          0
gender               0
address              0
per_capita_income    0
yearly_income        0
total_debt           0
credit_score         0
num_credit_cards     0
transaction_id       0
date                 0
client_id            0
card_id              0
amount               0
use_chip             0
merchant_id          0
merchant_city        0
merchant_state       0
zip                  0
dtype: int64

=== DATA TYPES ===
id                     int64
current_age            int64
birth_year             int64
birth_month            int64
gender                   str
address                  str
per_capita_income      int64
yearly_income          int64
total_debt             int64
credit_score           int64
num_credit_cards       int64
transaction_id         int64
date                     str
client_id                str
card_id                  str
amount               float64
use_chip                 str
merchant_id              str
merchant_city            str
merchant_state           str
zip                    int64
dtype: object

=== UNIQUE VALUES ===
id                   20000
current_age             52
birth_year              52
birth_month             12
gender                   3
address               4938
per_capita_income     4730
yearly_income         4867
total_debt            3156
credit_score           394
num_credit_cards         5
transaction_id       13028
date                  1035
client_id             4941
card_id              10030
amount               19656
use_chip                 2
merchant_id            500
merchant_city           15
merchant_state          11
zip                   4140
dtype: int64

=== NUMERIC SUMMARY ===

,count,mean,std,min,25%,50%,75%,max
id,20000.0,10000.500000,5773.647028,1.00,5000.7500,10000.50,15000.250,20000.00
current_age,20000.0,44.210100,14.992515,19.00,31.0000,44.00,57.000,70.00
birth_year,20000.0,1980.789900,14.992515,1955.00,1968.0000,1981.00,1994.000,2006.00
birth_month,20000.0,6.479150,3.459532,1.00,3.0000,7.00,10.000,12.00
per_capita_income,20000.0,61234.419700,35354.273099,12500.00,35671.0000,54896.00,74842.000,250000.00
yearly_income,20000.0,734813.051800,424251.190541,150000.00,428047.0000,658756.00,898109.000,3000000.00
total_debt,20000.0,134537.985500,173975.716361,0.00,0.0000,82503.00,200872.000,1817384.00
credit_score,20000.0,702.979750,76.993944,421.00,648.0000,699.00,757.000,900.00
num_credit_cards,20000.0,2.873750,1.162574,1.00,2.0000,3.00,4.000,5.00
transaction_id,20000.0,10015.488700,5802.389323,1.00,4971.0000,10026.50,15062.750,20000.00
amount,20000.0,3082.286901,2117.081361,105.16,1531.1825,2601.65,4116.155,19806.63
zip,20000.0,445976.994400,168230.579911,110102.00,380703.5000,440388.00,560252.000,800988.00

=== CATEGORICAL VALUES ===

gender:
gender
Male      9855
Female    9479
Other      666
Name: count, dtype: int64

use_chip:
use_chip
Yes    13927
No      6073
Name: count, dtype: int64

merchant_state:
merchant_state
Maharashtra       4132
Gujarat           3043
Madhya Pradesh    2584
Karnataka         1567
Uttar Pradesh     1435
Telangana         1352
Bihar             1311
Rajasthan         1288
Tamil Nadu        1284
Delhi             1079
West Bengal        925
Name: count, dtype: int64

=== SAMPLE RECORDS ===

,id,current_age,birth_year,birth_month,gender,address,per_capita_income,yearly_income,total_debt,credit_score,...,transaction_id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip
0,1,64,1961,3,Female,"Street 286, Indore, Madhya Pradesh - 452645",86125,1033501,280435,715,...,1251,2024-03-28,CLTIND00104,CRD001042,1483.94,Yes,MCH00496,Mumbai,Maharashtra,452645
1,2,39,1986,12,Female,"Street 268, Kolkata, West Bengal - 700555",68414,820965,0,834,...,9976,2025-09-20,CLTIND00213,CRD002132,1274.72,Yes,MCH00374,Mumbai,Maharashtra,700555
2,3,50,1975,7,Female,"Street 262, Lucknow, Uttar Pradesh - 226797",22595,271138,0,609,...,6084,2024-10-02,CLTIND03292,CRD032922,7622.04,No,MCH00108,Kolkata,West Bengal,226797
3,4,27,1998,2,Male,"Street 265, Nagpur, Maharashtra - 440623",24158,289898,0,782,...,3350,2023-09-02,CLTIND05205,CRD052053,3970.48,Yes,MCH00001,Indore,Madhya Pradesh,440623
4,5,45,1980,7,Other,"Street 157, Delhi, Delhi - 110965",45475,545697,117821,608,...,11725,2025-05-25,CLTIND04910,CRD049101,418.45,No,MCH00254,Bengaluru,Karnataka,110965
5,6,23,2002,6,Female,"Street 161, Nagpur, Maharashtra - 440496",57403,688831,207894,652,...,3728,2025-10-21,CLTIND01637,CRD016374,5533.61,Yes,MCH00127,Indore,Madhya Pradesh,440496
6,7,20,2005,3,Male,"Street 131, Delhi, Delhi - 110284",37412,448940,0,724,...,487,2025-02-12,CLTIND02181,CRD021811,1840.93,Yes,MCH00228,Chennai,Tamil Nadu,110284
7,8,32,1993,1,Male,"Street 198, Chennai, Tamil Nadu - 600164",48926,587118,31674,684,...,11140,2024-03-19,CLTIND03537,CRD035372,5168.03,Yes,MCH00306,Surat,Gujarat,600164
8,9,70,1955,12,Female,"Street 170, Pune, Maharashtra - 411853",26481,317771,0,800,...,3517,2024-03-14,CLTIND00107,CRD001071,3343.60,No,MCH00270,Bhopal,Madhya Pradesh,411853
9,10,65,1960,8,Female,"Street 114, Nagpur, Maharashtra - 440442",28077,336928,30790,728,...,3081,2023-06-24,CLTIND02589,CRD025891,3297.57,No,MCH00058,Lucknow,Uttar Pradesh,440442

In [3]:
print("Date examples:")
print(df["date"].head(10).tolist())

print("\nDate range:")
print(df["date"].min(), "to", df["date"].max())

Date examples:
['2024-03-28', '2025-09-20', '2024-10-02', '2023-09-02', '2025-05-25', '2025-10-21', '2025-02-12', '2024-03-19', '2024-03-14', '2023-06-24']

Date range:
2023-01-01 to 2025-10-31

In [4]:
import pandas as pd
import numpy as np

# Load original dataset
df = pd.read_csv("../financial/Customer_Financial_Profiles.csv")

print("Original Shape:", df.shape)


# --------------------------------------------------
# 1. STANDARDIZE COLUMN NAMES
# --------------------------------------------------

df.columns = [
    "CustomerID",
    "CurrentAge",
    "BirthYear",
    "BirthMonth",
    "Gender",
    "Address",
    "PerCapitaIncome",
    "YearlyIncome",
    "TotalDebt",
    "CreditScore",
    "NumCreditCards",
    "TransactionID",
    "Date",
    "ClientID",
    "CardID",
    "Amount",
    "UseChip",
    "MerchantID",
    "MerchantCity",
    "MerchantState",
    "Zip"
]


# --------------------------------------------------
# 2. DATA TYPE CONVERSION
# --------------------------------------------------

numeric_cols = [
    "CustomerID",
    "CurrentAge",
    "BirthYear",
    "BirthMonth",
    "PerCapitaIncome",
    "YearlyIncome",
    "TotalDebt",
    "CreditScore",
    "NumCreditCards",
    "Amount"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")


# Convert date to datetime
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")


# IDs are identifiers, not measures
id_cols = [
    "TransactionID",
    "ClientID",
    "CardID",
    "MerchantID"
]

for col in id_cols:
    df[col] = df[col].astype(str).str.strip()


# Clean categorical columns
categorical_cols = [
    "Gender",
    "UseChip",
    "MerchantCity",
    "MerchantState"
]

for col in categorical_cols:
    df[col] = df[col].astype(str).str.strip()


# Zip code is a geographic identifier
df["Zip"] = df["Zip"].astype(str).str.replace(".0", "", regex=False)


# --------------------------------------------------
# 3. REMOVE EXACT DUPLICATES
# --------------------------------------------------

duplicates_before = df.duplicated().sum()

df = df.drop_duplicates()

duplicates_after = df.duplicated().sum()

print("Duplicates before cleaning:", duplicates_before)
print("Duplicates after cleaning:", duplicates_after)


# --------------------------------------------------
# 4. FEATURE ENGINEERING
# --------------------------------------------------

# Debt-to-Income Ratio
df["DebtToIncomeRatio"] = np.where(
    df["YearlyIncome"] > 0,
    (df["TotalDebt"] / df["YearlyIncome"]) * 100,
    0
)


# Age Groups
df["AgeGroup"] = pd.cut(
    df["CurrentAge"],
    bins=[18, 25, 35, 45, 55, 65, 100],
    labels=[
        "19-25",
        "26-35",
        "36-45",
        "46-55",
        "56-65",
        "66+"
    ]
)


# Credit Score Category
df["CreditScoreCategory"] = pd.cut(
    df["CreditScore"],
    bins=[0, 579, 669, 739, 799, 900],
    labels=[
        "Poor",
        "Fair",
        "Good",
        "Very Good",
        "Excellent"
    ]
)


# Income Category
df["IncomeCategory"] = pd.qcut(
    df["YearlyIncome"],
    q=4,
    labels=[
        "Low Income",
        "Lower-Middle Income",
        "Upper-Middle Income",
        "High Income"
    ]
)


# Debt Status
df["DebtStatus"] = np.where(
    df["TotalDebt"] == 0,
    "No Debt",
    "Has Debt"
)


# Transaction Amount Category
df["TransactionAmountCategory"] = pd.cut(
    df["Amount"],
    bins=[0, 1000, 5000, 10000, np.inf],
    labels=[
        "Low",
        "Medium",
        "High",
        "Very High"
    ]
)


# Date-based features
df["TransactionYear"] = df["Date"].dt.year
df["TransactionMonth"] = df["Date"].dt.month
df["TransactionMonthName"] = df["Date"].dt.month_name()
df["TransactionQuarter"] = "Q" + df["Date"].dt.quarter.astype(str)


# --------------------------------------------------
# 5. VALIDATION
# --------------------------------------------------

print("\n=== CLEANED DATASET ===")
print("Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nCredit Score Range:")
print(df["CreditScore"].min(), "to", df["CreditScore"].max())

print("\nAge Range:")
print(df["CurrentAge"].min(), "to", df["CurrentAge"].max())

print("\nTransaction Amount Range:")
print(df["Amount"].min(), "to", df["Amount"].max())

print("\nDebt-to-Income Ratio Range:")
print(
    round(df["DebtToIncomeRatio"].min(), 2),
    "to",
    round(df["DebtToIncomeRatio"].max(), 2)
)

print("\nFinal Columns:")
print(df.columns.tolist())

display(df.head())

Original Shape: (20000, 21)
Duplicates before cleaning: 0
Duplicates after cleaning: 0

=== CLEANED DATASET ===
Shape: (20000, 31)

Missing Values:
CustomerID                   0
CurrentAge                   0
BirthYear                    0
BirthMonth                   0
Gender                       0
Address                      0
PerCapitaIncome              0
YearlyIncome                 0
TotalDebt                    0
CreditScore                  0
NumCreditCards               0
TransactionID                0
Date                         0
ClientID                     0
CardID                       0
Amount                       0
UseChip                      0
MerchantID                   0
MerchantCity                 0
MerchantState                0
Zip                          0
DebtToIncomeRatio            0
AgeGroup                     0
CreditScoreCategory          0
IncomeCategory               0
DebtStatus                   0
TransactionAmountCategory    0
TransactionYear              0
TransactionMonth             0
TransactionMonthName         0
TransactionQuarter           0
dtype: int64

Duplicate Rows:
0

Credit Score Range:
421 to 900

Age Range:
19 to 70

Transaction Amount Range:
105.16 to 19806.63

Debt-to-Income Ratio Range:
0.0 to 82.92

Final Columns:
['CustomerID', 'CurrentAge', 'BirthYear', 'BirthMonth', 'Gender', 'Address', 'PerCapitaIncome', 'YearlyIncome', 'TotalDebt', 'CreditScore', 'NumCreditCards', 'TransactionID', 'Date', 'ClientID', 'CardID', 'Amount', 'UseChip', 'MerchantID', 'MerchantCity', 'MerchantState', 'Zip', 'DebtToIncomeRatio', 'AgeGroup', 'CreditScoreCategory', 'IncomeCategory', 'DebtStatus', 'TransactionAmountCategory', 'TransactionYear', 'TransactionMonth', 'TransactionMonthName', 'TransactionQuarter']

,CustomerID,CurrentAge,BirthYear,BirthMonth,Gender,Address,PerCapitaIncome,YearlyIncome,TotalDebt,CreditScore,...,DebtToIncomeRatio,AgeGroup,CreditScoreCategory,IncomeCategory,DebtStatus,TransactionAmountCategory,TransactionYear,TransactionMonth,TransactionMonthName,TransactionQuarter
0,1,64,1961,3,Female,"Street 286, Indore, Madhya Pradesh - 452645",86125,1033501,280435,715,...,27.134468,56-65,Good,High Income,Has Debt,Medium,2024,3,March,Q1
1,2,39,1986,12,Female,"Street 268, Kolkata, West Bengal - 700555",68414,820965,0,834,...,0.000000,36-45,Excellent,Upper-Middle Income,No Debt,Medium,2025,9,September,Q3
2,3,50,1975,7,Female,"Street 262, Lucknow, Uttar Pradesh - 226797",22595,271138,0,609,...,0.000000,46-55,Fair,Low Income,No Debt,High,2024,10,October,Q4
3,4,27,1998,2,Male,"Street 265, Nagpur, Maharashtra - 440623",24158,289898,0,782,...,0.000000,26-35,Very Good,Low Income,No Debt,Medium,2023,9,September,Q3
4,5,45,1980,7,Other,"Street 157, Delhi, Delhi - 110965",45475,545697,117821,608,...,21.590920,36-45,Fair,Lower-Middle Income,Has Debt,Low,2025,5,May,Q2

In [5]:
# Detailed validation of engineered financial features

print("=== AGE GROUP ===")
print(df["AgeGroup"].value_counts().sort_index())

print("\n=== CREDIT SCORE CATEGORY ===")
print(df["CreditScoreCategory"].value_counts())

print("\n=== INCOME CATEGORY ===")
print(df["IncomeCategory"].value_counts())

print("\n=== DEBT STATUS ===")
print(df["DebtStatus"].value_counts())

print("\n=== TRANSACTION AMOUNT CATEGORY ===")
print(df["TransactionAmountCategory"].value_counts())

print("\n=== TRANSACTION YEAR ===")
print(df["TransactionYear"].value_counts().sort_index())

print("\n=== PAYMENT METHOD ===")
print(df["UseChip"].value_counts())

print("\n=== MERCHANT STATE ===")
print(df["MerchantState"].value_counts())

print("\n=== FINANCIAL SUMMARY ===")
display(
    df[
        [
            "PerCapitaIncome",
            "YearlyIncome",
            "TotalDebt",
            "CreditScore",
            "NumCreditCards",
            "Amount",
            "DebtToIncomeRatio"
        ]
    ].describe().T
)

=== AGE GROUP ===
AgeGroup
19-25    2924
26-35    3686
36-45    3800
46-55    3919
56-65    3884
66+      1787
Name: count, dtype: int64

=== CREDIT SCORE CATEGORY ===
CreditScoreCategory
Good         6819
Fair         5960
Very Good    3943
Excellent    2300
Poor          978
Name: count, dtype: int64

=== INCOME CATEGORY ===
IncomeCategory
Low Income             5003
Lower-Middle Income    5000
High Income            4999
Upper-Middle Income    4998
Name: count, dtype: int64

=== DEBT STATUS ===
DebtStatus
Has Debt    12896
No Debt      7104
Name: count, dtype: int64

=== TRANSACTION AMOUNT CATEGORY ===
TransactionAmountCategory
Medium       14301
High          3013
Low           2480
Very High      206
Name: count, dtype: int64

=== TRANSACTION YEAR ===
TransactionYear
2023    7101
2024    7045
2025    5854
Name: count, dtype: int64

=== PAYMENT METHOD ===
UseChip
Yes    13927
No      6073
Name: count, dtype: int64

=== MERCHANT STATE ===
MerchantState
Maharashtra       4132
Gujarat           3043
Madhya Pradesh    2584
Karnataka         1567
Uttar Pradesh     1435
Telangana         1352
Bihar             1311
Rajasthan         1288
Tamil Nadu        1284
Delhi             1079
West Bengal        925
Name: count, dtype: int64

=== FINANCIAL SUMMARY ===

,count,mean,std,min,25%,50%,75%,max
PerCapitaIncome,20000.0,61234.419700,35354.273099,12500.00,35671.0000,54896.000000,74842.000000,2.500000e+05
YearlyIncome,20000.0,734813.051800,424251.190541,150000.00,428047.0000,658756.000000,898109.000000,3.000000e+06
TotalDebt,20000.0,134537.985500,173975.716361,0.00,0.0000,82503.000000,200872.000000,1.817384e+06
CreditScore,20000.0,702.979750,76.993944,421.00,648.0000,699.000000,757.000000,9.000000e+02
NumCreditCards,20000.0,2.873750,1.162574,1.00,2.0000,3.000000,4.000000,5.000000e+00
Amount,20000.0,3082.286901,2117.081361,105.16,1531.1825,2601.650000,4116.155000,1.980663e+04
DebtToIncomeRatio,20000.0,18.269472,18.402944,0.00,0.0000,15.008475,31.520379,8.292256e+01

In [6]:
# Save cleaned financial dataset

output_path = "../financial/Customer_Financial_Profiles_Cleaned.csv"

df.to_csv(output_path, index=False)

print("Cleaned dataset saved successfully!")
print("File:", output_path)
print("Shape:", df.shape)

Cleaned dataset saved successfully!
File: ../financial/Customer_Financial_Profiles_Cleaned.csv
Shape: (20000, 31)

In [7]:
%pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\shreya\appdata\local\programs\python\python312\lib\site-packages (26.7.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import pandas as pd
import mysql.connector

# Load cleaned dataset
df = pd.read_csv("../financial/Customer_Financial_Profiles_Cleaned.csv")

# Convert date to proper MySQL date format
df["Date"] = pd.to_datetime(df["Date"]).dt.date

print("Rows to insert:", len(df))
print("Columns:", len(df.columns))

Rows to insert: 20000
Columns: 31

In [9]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="root",
    database="financial_analytics"
)

cursor = conn.cursor()

print("MySQL connection successful!")

MySQL connection successful!

In [10]:
insert_sql = """
INSERT INTO customer_financial_profiles (
    CustomerID,
    CurrentAge,
    BirthYear,
    BirthMonth,
    Gender,
    Address,
    PerCapitaIncome,
    YearlyIncome,
    TotalDebt,
    CreditScore,
    NumCreditCards,
    TransactionID,
    Date,
    ClientID,
    CardID,
    Amount,
    UseChip,
    MerchantID,
    MerchantCity,
    MerchantState,
    Zip,
    DebtToIncomeRatio,
    AgeGroup,
    CreditScoreCategory,
    IncomeCategory,
    DebtStatus,
    TransactionAmountCategory,
    TransactionYear,
    TransactionMonth,
    TransactionMonthName,
    TransactionQuarter
)
VALUES (
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s
)
"""

records = [
    tuple(row)
    for row in df[
        [
            "CustomerID",
            "CurrentAge",
            "BirthYear",
            "BirthMonth",
            "Gender",
            "Address",
            "PerCapitaIncome",
            "YearlyIncome",
            "TotalDebt",
            "CreditScore",
            "NumCreditCards",
            "TransactionID",
            "Date",
            "ClientID",
            "CardID",
            "Amount",
            "UseChip",
            "MerchantID",
            "MerchantCity",
            "MerchantState",
            "Zip",
            "DebtToIncomeRatio",
            "AgeGroup",
            "CreditScoreCategory",
            "IncomeCategory",
            "DebtStatus",
            "TransactionAmountCategory",
            "TransactionYear",
            "TransactionMonth",
            "TransactionMonthName",
            "TransactionQuarter"
        ]
    ].itertuples(index=False, name=None)
]

In [11]:
for i in range(0, len(records), 5000):
    batch = records[i:i+5000]

    cursor.executemany(insert_sql, batch)
    conn.commit()

    print(f"Inserted {min(i + 5000, len(records))} / {len(records)} rows")

Inserted 5000 / 20000 rows
Inserted 10000 / 20000 rows
Inserted 15000 / 20000 rows
Inserted 20000 / 20000 rows

In [12]:
cursor.execute(
    "SELECT COUNT(*) FROM customer_financial_profiles"
)

count = cursor.fetchone()[0]

print("Rows in MySQL:", count)

Rows in MySQL: 20000

In [13]:
cursor.execute("""
    SELECT
        CustomerID,
        ClientID,
        CreditScore,
        YearlyIncome,
        TotalDebt,
        Amount,
        CreditScoreCategory,
        DebtToIncomeRatio
    FROM customer_financial_profiles
    LIMIT 5
""")

for row in cursor.fetchall():
    print(row)

(1, 'CLTIND00104', 715, Decimal('1033501.00'), Decimal('280435.00'), Decimal('1483.94'), 'Good', Decimal('27.13'))
(2, 'CLTIND00213', 834, Decimal('820965.00'), Decimal('0.00'), Decimal('1274.72'), 'Excellent', Decimal('0.00'))
(3, 'CLTIND03292', 609, Decimal('271138.00'), Decimal('0.00'), Decimal('7622.04'), 'Fair', Decimal('0.00'))
(4, 'CLTIND05205', 782, Decimal('289898.00'), Decimal('0.00'), Decimal('3970.48'), 'Very Good', Decimal('0.00'))
(5, 'CLTIND04910', 608, Decimal('545697.00'), Decimal('117821.00'), Decimal('418.45'), 'Fair', Decimal('21.59'))

In [14]:
cursor.close()
conn.close()

print("MySQL connection closed.")

MySQL connection closed.