In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv(
    "../healthcare/Synthetic_patient-HealthCare-Monitoring_dataset.csv"
)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [6]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 60000
Columns: 13

In [7]:
df.head()

,Patient Number,Heart Rate (bpm),SpO2 Level (%),Systolic Blood Pressure (mmHg),Diastolic Blood Pressure (mmHg),Body Temperature (°C),Fall Detection,Predicted Disease,Data Accuracy (%),Heart Rate Alert,SpO2 Level Alert,Blood Pressure Alert,Temperature Alert
0,1,98,96,120,86,38.1,No,Diabetes Mellitus,95,NORMAL,NORMAL,NORMAL,ABNORMAL
1,2,105,97,177,104,37.6,No,Heart Disease,91,ABNORMAL,NORMAL,ABNORMAL,ABNORMAL
2,3,90,85,139,57,37.0,No,Asthma,98,NORMAL,ABNORMAL,NORMAL,NORMAL
3,4,102,87,101,77,36.4,No,Asthma,87,ABNORMAL,ABNORMAL,NORMAL,NORMAL
4,5,81,95,172,119,37.7,No,Hypertension,88,NORMAL,NORMAL,ABNORMAL,ABNORMAL

In [8]:
df.tail()

,Patient Number,Heart Rate (bpm),SpO2 Level (%),Systolic Blood Pressure (mmHg),Diastolic Blood Pressure (mmHg),Body Temperature (°C),Fall Detection,Predicted Disease,Data Accuracy (%),Heart Rate Alert,SpO2 Level Alert,Blood Pressure Alert,Temperature Alert
59995,59996,84,93,135,108,38.5,No,Diabetes Mellitus,100,NORMAL,ABNORMAL,ABNORMAL,ABNORMAL
59996,59997,67,99,111,72,36.7,No,Healthy,97,NORMAL,NORMAL,NORMAL,NORMAL
59997,59998,75,99,115,75,36.8,No,Healthy,95,NORMAL,NORMAL,NORMAL,NORMAL
59998,59999,70,99,117,70,36.6,No,Healthy,96,NORMAL,NORMAL,NORMAL,NORMAL
59999,60000,97,96,108,92,38.5,No,Diabetes Mellitus,100,NORMAL,NORMAL,ABNORMAL,ABNORMAL

In [9]:
df.describe()

,Patient Number,Heart Rate (bpm),SpO2 Level (%),Systolic Blood Pressure (mmHg),Diastolic Blood Pressure (mmHg),Body Temperature (°C),Data Accuracy (%)
count,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000
mean,30000.500000,94.571150,94.553433,139.152733,88.954633,37.121432,92.511417
std,17320.652413,18.376105,3.843543,26.933776,17.856562,0.626535,4.609298
min,1.000000,50.000000,84.000000,90.000000,50.000000,35.000000,85.000000
25%,15000.750000,82.000000,92.000000,116.000000,75.000000,36.700000,89.000000
50%,30000.500000,95.000000,96.000000,138.000000,89.000000,37.000000,93.000000
75%,45000.250000,106.000000,98.000000,161.000000,102.000000,37.600000,97.000000
max,60000.000000,139.000000,100.000000,199.000000,130.000000,39.300000,100.000000

In [10]:
print("Column Names:")
for col in df.columns:
    print(col)

Column Names:
Patient Number
Heart Rate (bpm)
SpO2 Level (%)
Systolic Blood Pressure (mmHg)
Diastolic Blood Pressure (mmHg)
Body Temperature (°C)
Fall Detection
Predicted Disease
Data Accuracy (%)
Heart Rate Alert
SpO2 Level Alert
Blood Pressure Alert
Temperature Alert

In [11]:
missing_values = df.isnull().sum()

print("Missing Values:")
print(missing_values)

Missing Values:
Patient Number                     0
Heart Rate (bpm)                   0
SpO2 Level (%)                     0
Systolic Blood Pressure (mmHg)     0
Diastolic Blood Pressure (mmHg)    0
Body Temperature (°C)              0
Fall Detection                     0
Predicted Disease                  0
Data Accuracy (%)                  0
Heart Rate Alert                   0
SpO2 Level Alert                   0
Blood Pressure Alert               0
Temperature Alert                  0
dtype: int64

In [12]:
print("Total missing values:", df.isnull().sum().sum())

Total missing values: 0

In [13]:
duplicate_count = df.duplicated().sum()

print("Duplicate records:", duplicate_count)

Duplicate records: 0

In [14]:
if duplicate_count > 0:
    df = df.drop_duplicates()
    print("Duplicate records removed.")
else:
    print("No duplicate records found.")

No duplicate records found.

In [15]:
print(df.dtypes)

Patient Number                       int64
Heart Rate (bpm)                     int64
SpO2 Level (%)                       int64
Systolic Blood Pressure (mmHg)       int64
Diastolic Blood Pressure (mmHg)      int64
Body Temperature (°C)              float64
Fall Detection                         str
Predicted Disease                      str
Data Accuracy (%)                    int64
Heart Rate Alert                       str
SpO2 Level Alert                       str
Blood Pressure Alert                   str
Temperature Alert                      str
dtype: object

In [16]:
df.rename(columns={
    "Patient Number": "PatientID",
    "Heart Rate (bpm)": "HeartRate",
    "SpO2 Level (%)": "SpO2",
    "Systolic Blood Pressure (mmHg)": "SystolicBP",
    "Diastolic Blood Pressure (mmHg)": "DiastolicBP",
    "Body Temperature (°C)": "BodyTemperature",
    "Fall Detection": "FallDetection",
    "Predicted Disease": "PredictedDisease",
    "Data Accuracy (%)": "DataAccuracy",
    "Heart Rate Alert": "HeartRateAlert",
    "SpO2 Level Alert": "SpO2Alert",
    "Blood Pressure Alert": "BloodPressureAlert",
    "Temperature Alert": "TemperatureAlert"
}, inplace=True)

print(df.columns.tolist())

['PatientID', 'HeartRate', 'SpO2', 'SystolicBP', 'DiastolicBP', 'BodyTemperature', 'FallDetection', 'PredictedDisease', 'DataAccuracy', 'HeartRateAlert', 'SpO2Alert', 'BloodPressureAlert', 'TemperatureAlert']

In [17]:
numeric_columns = [
    "PatientID",
    "HeartRate",
    "SpO2",
    "SystolicBP",
    "DiastolicBP",
    "BodyTemperature",
    "DataAccuracy"
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print(df[numeric_columns].dtypes)

PatientID            int64
HeartRate            int64
SpO2                 int64
SystolicBP           int64
DiastolicBP          int64
BodyTemperature    float64
DataAccuracy         int64
dtype: object

In [18]:
print("Missing values after numeric conversion:")
print(df[numeric_columns].isnull().sum())

Missing values after numeric conversion:
PatientID          0
HeartRate          0
SpO2               0
SystolicBP         0
DiastolicBP        0
BodyTemperature    0
DataAccuracy       0
dtype: int64

In [19]:
print(
    "Total missing values after conversion:",
    df.isnull().sum().sum()
)

Total missing values after conversion: 0

In [20]:
categorical_columns = [
    "FallDetection",
    "PredictedDisease",
    "HeartRateAlert",
    "SpO2Alert",
    "BloodPressureAlert",
    "TemperatureAlert"
]

for col in categorical_columns:
    print("\n", col)
    print(df[col].value_counts())

 FallDetection
FallDetection
No     56926
Yes     3074
Name: count, dtype: int64

 PredictedDisease
PredictedDisease
Diabetes Mellitus    12167
Heart Disease        12044
Healthy              11973
Hypertension         11928
Asthma               11888
Name: count, dtype: int64

 HeartRateAlert
HeartRateAlert
NORMAL      36992
ABNORMAL    23008
Name: count, dtype: int64

 SpO2Alert

SpO2Alert
NORMAL      34770
ABNORMAL    25230
Name: count, dtype: int64

 BloodPressureAlert
BloodPressureAlert
ABNORMAL    33470
NORMAL      26530
Name: count, dtype: int64

 TemperatureAlert
TemperatureAlert
NORMAL      44656
ABNORMAL    15344
Name: count, dtype: int64

In [21]:
for col in categorical_columns:
    df[col] = df[col].astype(str).str.strip()

In [22]:
print("Heart Rate range:")
print(df["HeartRate"].min(), "to", df["HeartRate"].max())

print("\nSpO2 range:")
print(df["SpO2"].min(), "to", df["SpO2"].max())

print("\nSystolic BP range:")
print(df["SystolicBP"].min(), "to", df["SystolicBP"].max())

print("\nDiastolic BP range:")
print(df["DiastolicBP"].min(), "to", df["DiastolicBP"].max())

print("\nBody Temperature range:")
print(df["BodyTemperature"].min(), "to", df["BodyTemperature"].max())

print("\nData Accuracy range:")
print(df["DataAccuracy"].min(), "to", df["DataAccuracy"].max())

Heart Rate range:
50 to 139

SpO2 range:
84 to 100

Systolic BP range:
90 to 199

Diastolic BP range:
50 to 130

Body Temperature range:
35.0 to 39.3

Data Accuracy range:
85 to 100

In [23]:
numeric_analysis_columns = [
    "HeartRate",
    "SpO2",
    "SystolicBP",
    "DiastolicBP",
    "BodyTemperature",
    "DataAccuracy"
]

for col in numeric_analysis_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower_bound) |
        (df[col] > upper_bound)
    ]

    print(f"{col}: {len(outliers)} potential statistical outliers")

HeartRate: 0 potential statistical outliers
SpO2: 0 potential statistical outliers
SystolicBP: 0 potential statistical outliers
DiastolicBP: 0 potential statistical outliers
BodyTemperature: 135 potential statistical outliers

DataAccuracy: 0 potential statistical outliers

In [24]:
df["PulsePressure"] = (
    df["SystolicBP"] - df["DiastolicBP"]
)

In [25]:
df["MeanArterialPressure"] = (
    df["SystolicBP"] +
    (2 * df["DiastolicBP"])
) / 3

In [26]:
alert_columns = [
    "HeartRateAlert",
    "SpO2Alert",
    "BloodPressureAlert",
    "TemperatureAlert"
]

df["AbnormalVitalCount"] = (
    df[alert_columns]
    .eq("ABNORMAL")
    .sum(axis=1)
)

In [27]:
df["HealthAlertLevel"] = pd.cut(
    df["AbnormalVitalCount"],
    bins=[-1, 0, 1, 2, 4],
    labels=[
        "Normal",
        "Low",
        "Moderate",
        "High"
    ]
)

In [28]:
df["AccuracyCategory"] = pd.cut(
    df["DataAccuracy"],
    bins=[84, 89, 94, 97, 100],
    labels=[
        "Acceptable",
        "Good",
        "Very Good",
        "Excellent"
    ]
)

In [29]:
print("Final Shape:", df.shape)

Final Shape: (60000, 18)

In [30]:
df.head()

,PatientID,HeartRate,SpO2,SystolicBP,DiastolicBP,BodyTemperature,FallDetection,PredictedDisease,DataAccuracy,HeartRateAlert,SpO2Alert,BloodPressureAlert,TemperatureAlert,PulsePressure,MeanArterialPressure,AbnormalVitalCount,HealthAlertLevel,AccuracyCategory
0,1,98,96,120,86,38.1,No,Diabetes Mellitus,95,NORMAL,NORMAL,NORMAL,ABNORMAL,34,97.333333,1,Low,Very Good
1,2,105,97,177,104,37.6,No,Heart Disease,91,ABNORMAL,NORMAL,ABNORMAL,ABNORMAL,73,128.333333,3,High,Good
2,3,90,85,139,57,37.0,No,Asthma,98,NORMAL,ABNORMAL,NORMAL,NORMAL,82,84.333333,1,Low,Excellent
3,4,102,87,101,77,36.4,No,Asthma,87,ABNORMAL,ABNORMAL,NORMAL,NORMAL,24,85.000000,2,Moderate,Acceptable
4,5,81,95,172,119,37.7,No,Hypertension,88,NORMAL,NORMAL,ABNORMAL,ABNORMAL,53,136.666667,2,Moderate,Acceptable

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PatientID             60000 non-null  int64
 1   HeartRate             60000 non-null  int64
 2   SpO2                  60000 non-null  int64
 3   SystolicBP            60000 non-null  int64
 4   DiastolicBP           60000 non-null  int64
 5   BodyTemperature       60000 non-null  float64
 6   FallDetection         60000 non-null  str
 7   PredictedDisease      60000 non-null  str
 8   DataAccuracy          60000 non-null  int64
 9   HeartRateAlert        60000 non-null  str
 10  SpO2Alert             60000 non-null  str
 11  BloodPressureAlert    60000 non-null  str
 12  TemperatureAlert      60000 non-null  str
 13  PulsePressure         60000 non-null  int64
 14  MeanArterialPressure  60000 non-null  float64
 15  AbnormalVitalCount    60000 non-null  int64
 16  HealthAlertLevel      60000 non-null  category
 17  AccuracyCategory      60000 non-null  category
dtypes: category(2), float64(2), int64(8), str(6)
memory usage: 7.4 MB

In [32]:
print("Final Missing Values:")
print(df.isnull().sum())

Final Missing Values:
PatientID               0
HeartRate               0
SpO2                    0
SystolicBP              0
DiastolicBP             0
BodyTemperature         0
FallDetection           0
PredictedDisease        0
DataAccuracy            0
HeartRateAlert          0
SpO2Alert               0
BloodPressureAlert      0
TemperatureAlert        0
PulsePressure           0
MeanArterialPressure    0
AbnormalVitalCount      0
HealthAlertLevel        0
AccuracyCategory        0
dtype: int64

In [33]:
print(
    "Total Missing Values:",
    df.isnull().sum().sum()
)

Total Missing Values: 0

In [34]:
print(
    "Final Duplicate Records:",
    df.duplicated().sum()
)

Final Duplicate Records: 0

In [35]:
import sys
print(sys.executable)

c:\Users\shreya\AppData\Local\Python\pythoncore-3.14-64\python.exe

In [36]:
%pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\Users\shreya\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (26.7.0)
Note: you may need to restart the kernel to use updated packages.

In [37]:
import mysql.connector

print("MySQL connector imported successfully!")

MySQL connector imported successfully!

In [38]:
cleaned_df = pd.read_csv(
    "../healthcare/Patient_Data_Healthcare_Cleaned.csv"
)

print("Rows:", cleaned_df.shape[0])
print("Columns:", cleaned_df.shape[1])

Rows: 60000
Columns: 18

In [ ]:
from getpass import getpass

mysql_password = getpass("Enter MySQL root password: ")

connection = mysql.connector.connect(
    host="localhost",
    port=3306,
    user="root",
    password=mysql_password,
    database="healthcare_analytics"
)

print("MySQL connection successful!")

In [ ]:
cursor = connection.cursor()

cursor.execute("""
    SELECT COUNT(*)
    FROM patient_monitoring
""")

current_count = cursor.fetchone()[0]

print("Current records in MySQL:", current_count)

Current records in MySQL: 0

In [ ]:
insert_query = """
INSERT INTO patient_monitoring (
    PatientID,
    HeartRate,
    SpO2,
    SystolicBP,
    DiastolicBP,
    BodyTemperature,
    FallDetection,
    PredictedDisease,
    DataAccuracy,
    HeartRateAlert,
    SpO2Alert,
    BloodPressureAlert,
    TemperatureAlert,
    PulsePressure,
    MeanArterialPressure,
    AbnormalVitalCount,
    HealthAlertLevel,
    AccuracyCategory
)
VALUES (
    %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s
)
"""

batch_size = 5000
total_rows = len(cleaned_df)

for start in range(0, total_rows, batch_size):
    end = min(start + batch_size, total_rows)

    batch = cleaned_df.iloc[start:end]
    records = [
        tuple(row)
        for row in batch.itertuples(index=False, name=None)
    ]

    cursor.executemany(insert_query, records)
    connection.commit()

    print(f"Inserted {end} / {total_rows} records")

print("Data import completed successfully!")

Inserted 5000 / 60000 records
Inserted 10000 / 60000 records
Inserted 15000 / 60000 records
Inserted 20000 / 60000 records
Inserted 25000 / 60000 records
Inserted 30000 / 60000 records
Inserted 35000 / 60000 records
Inserted 40000 / 60000 records
Inserted 45000 / 60000 records
Inserted 50000 / 60000 records
Inserted 55000 / 60000 records
Inserted 60000 / 60000 records
Data import completed successfully!

In [ ]:
cursor.execute("SELECT COUNT(*) FROM patient_monitoring")

mysql_count = cursor.fetchone()[0]

print("Records in MySQL:", mysql_count)

Records in MySQL: 60000

In [ ]:
cursor.execute("""
    SELECT *
    FROM patient_monitoring
    LIMIT 5
""")

rows = cursor.fetchall()

for row in rows:
    print(row)

(1, 98, 96, 120, 86, Decimal('38.1'), 'No', 'Diabetes Mellitus', 95, 'NORMAL', 'NORMAL', 'NORMAL', 'ABNORMAL', 34, Decimal('97.33'), 1, 'Low', 'Very Good')
(2, 105, 97, 177, 104, Decimal('37.6'), 'No', 'Heart Disease', 91, 'ABNORMAL', 'NORMAL', 'ABNORMAL', 'ABNORMAL', 73, Decimal('128.33'), 3, 'High', 'Good')
(3, 90, 85, 139, 57, Decimal('37.0'), 'No', 'Asthma', 98, 'NORMAL', 'ABNORMAL', 'NORMAL', 'NORMAL', 82, Decimal('84.33'), 1, 'Low', 'Excellent')
(4, 102, 87, 101, 77, Decimal('36.4'), 'No', 'Asthma', 87, 'ABNORMAL', 'ABNORMAL', 'NORMAL', 'NORMAL', 24, Decimal('85.00'), 2, 'Moderate', 'Acceptable')
(5, 81, 95, 172, 119, Decimal('37.7'), 'No', 'Hypertension', 88, 'NORMAL', 'NORMAL', 'ABNORMAL', 'ABNORMAL', 53, Decimal('136.67'), 2, 'Moderate', 'Acceptable')

In [ ]:
cursor.close()
connection.close()

print("MySQL connection closed successfully!")

MySQL connection closed successfully!